Description: Base System
Name: base
Packages:
- alsa-utils
- audio-session-manager
- bash
- binutils
- bluetooth-frwk
- bluetooth-frwk-agent
- bluez
- bzip2
- ca-certificates
- cert-svc
- connman
- coreutils
- cpio
- dlogutil
- drm-service
- e2fsprogs
- filesystem
- gawk
- grep
- gzip
- insserv
- libsqlfs
- libss-client
- lsb
- mkdevnodes
- module-init-tools
- mtdev
- net-tools
- prelink
- procps
- psmisc
- pwdutils
- readline
- rfkill
- rpm
- sed
- sensor-framework
- setup
- net-config
- ss-server
- tar
- tizen-release
- tzdata-slp
- udev
- usbutils
- util-linux
- systemd
- systemd-sysv
Summary: Base System
